[tool.poetry]
name = "pixeltable"
version = "0.1.2"
description = "Pixeltable: a table interface to image and video data"
authors = ["Marcel Kornacker <marcelk@gmail.com>"]
readme = "README.md"
exclude = [
    ".pytype",
    ".pytest_cache",
    "pixeltable/.pytest_cache",
    "pixeltable/tests/data"
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.1"
pandas = "^1.5.3"
sqlalchemy-utils = "^0.39.0"
pillow = "^9.4.0"
opencv-python-headless = "^4.7.0.68"
tqdm = "^4.64.1"
sqlalchemy = "^1.4.41"
#torch = {version = "^1.13.1+cpu", source = "torchcpu"}
jmespath = "^1.0.1"
ftfy = "^6.1.1"
regex = "^2022.10.31"
hnswlib = "^0.6.2"
cloudpickle = "^2.2.1"
psycopg2-binary = "^2.9.5"
jinja2 = "^3.1.2"
docker = "^6.0.1"
open-clip-torch = "^2.16.0"
watchdog = "^3.0.0"
autonomi-nos = "0.0.4"

[tool.poetry.group.dev.dependencies]
tensorflow-io-gcs-filesystem = { version = "^0.28.0", python = ">=3.9,<3.11" }
tensorflow = "^2.11.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"

#[[tool.poetry.source]]
#name = "torchcpu"
#url = "https://download.pytorch.org/whl/cpu"
#default = false
#secondary = true



[tool.poetry.group.docs.dependencies]
sphinx = ">=5.2,<7"
sphinx-book-theme = "^1.0.1"
myst-nb = "^0.17.2"
myst-parser = ">=0.18,<0.19"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
