[tool.poetry]
name = "pixeltable"
version = "0.1.2"
description = "Pixeltable: a table interface to image and video data"
authors = ["Marcel Kornacker <marcelk@gmail.com>"]
readme = "README.md"
exclude = [
    ".pytype",
    ".pytest_cache",
    "pixeltable/.pytest_cache",
    "pixeltable/tests/data"
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.1"
pandas = "^1.5.3"
pillow = "^9.4.0"
opencv-python-headless = "^4.7.0.68"
tqdm = "^4.64.1"
jmespath = "^1.0.1"
ftfy = "^6.1.1"
regex = "^2022.10.31"
cloudpickle = "^2.2.1"
psycopg2-binary = "^2.9.5"
jinja2 = "^3.1.2"
docker = "^6.0.1"
psutil = "^5.9.5"
sqlalchemy = "^2.0.17"
sqlalchemy-utils = "^0.41.1"
autonomi-nos = {version = "^0.0.9", optional = true}
pgvector = "^0.2.1"
boto3 = {version = "^1.17", optional = true}
av = ">=10.0.0"
torch = {version = "^2.1.1", optional = true}
torchvision = {version = "^0.16.1", optional = true}
pyarrow = {version = ">=13.0.1", optional = true}
openai = {version = "^1.0.0", optional = true}

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-xdist = {extras = ["psutil"], version = "^3.3.1"}
torch = "^2.1.1"
torchvision = "^0.16.1"
pyarrow = ">=13.0.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = ">=5.2,<7"
sphinx-book-theme = "^1.0.1"
myst-nb = "^0.17.2"
myst-parser = ">=0.18,<0.19"

[tool.poetry.extras]
s3 = ["boto3"]
openai = ["openai"]
nos = ["autonomi-nos"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
